# Generated by Django 4.0.3 on 2022-05-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productstable_avilability'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=100, unique=True)),
                ('userid', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('stats', models.BooleanField(default=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstable')),
            ],
        ),
        migrations.CreateModel(
            name='cartlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart_id')),
            ],
        ),
    ]
