# Generated by Django 4.0.3 on 2022-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_id',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cart_id',
            name='userid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
