# Generated by Django 4.0.3 on 2022-05-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_id_session_alter_cart_id_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='productid',
        ),
        migrations.AlterField(
            model_name='recent',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart_id'),
        ),
    ]
