# Generated by Django 4.0.3 on 2022-05-23 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_and_prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='done_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
